# Generated by Django 2.1.7 on 2019-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190401_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menus',
            field=models.ManyToManyField(to='api.Menu'),
        ),
    ]
